import torch.nn as nn
import torchvision.models as models

from jaqpotpy import Jaqpot
from jaqpotpy.models.torch_models import TorchONNXModel
from jaqpot_api_client import ModelTask, Feature, FeatureType, ModelVisibility
import torch
import io
import torch.nn.functional as F
from jaqpotpy.jaqpot_local import JaqpotLocal


# -*- coding: utf-8 -*-
"""Nanomaterial classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f84QAJnnlksM4BoEUXYIO7II7rzkxLt4
"""


"""Create model"""


class NanomaterialClassifier(nn.Module):
    def __init__(self, num_classes=6):
        super().__init__()
        self.base = models.resnet18(pretrained=True)
        self.base.fc = nn.Linear(self.base.fc.in_features, num_classes)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        logits = self.base(x)
        probs = self.softmax(logits)
        return probs


model = NanomaterialClassifier(num_classes=6)

"""Load model from drive"""

model.load_state_dict(torch.load("./best_model.pth", map_location=torch.device("cpu")))
model.eval()

"""Upload to Jaqpot

1. Export trained model to ONNX
"""

# Load best model if not already loaded
# model.load_state_dict(torch.load("best_model.pth"))
model.eval()
# Dummy input to trace model shape: [1, 3, 224, 224]
dummy_input = torch.randn(1, 3, 224, 224).to(
    torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
)

"""2. Create and export image preprocessor to ONNX"""


class MyImagePreprocessor(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        # x: [batch, height, width, channels]
        x = x.permute(0, 3, 1, 2)  # NHWC → NCHW
        x = F.interpolate(x, size=(224, 224), mode="bilinear", align_corners=False)
        return x

    def export_to_onnx(self):
        dummy_preprocessor_input = torch.randn(1, 1024, 1280, 3)

        f = io.BytesIO()
        torch.onnx.export(
            self,
            dummy_preprocessor_input,
            f,
            input_names=["image"],  # must match inference input
            output_names=["tensor"],
            opset_version=11,
            dynamic_axes={"image": {0: "batch_size", 1: "height", 2: "width"}},
        )
        f.seek(0)
        return f.read()


"""3. Upload model to Jaqpot"""


# Create preprocessor object and export
preprocessor = MyImagePreprocessor()
onnx_preprocessor = preprocessor.export_to_onnx()

# Define features
independent_features = [
    Feature(key="input", name="Input Image", feature_type=FeatureType.IMAGE)
]

dependent_features = [
    Feature(key="class", name="Predicted Class", feature_type=FeatureType.STRING)
]

# Load exported model as torch.Tensor (or just use path)
input_tensor = torch.randn(1, 3, 224, 224)

# Create Jaqpot instance
jaqpot = Jaqpot()
jaqpot.login()

model.cpu()

# Define model for upload
jaqpot_model = TorchONNXModel(
    model,
    input_tensor,
    task=ModelTask.MULTICLASS_CLASSIFICATION,
    independent_features=independent_features,
    dependent_features=dependent_features,
    onnx_preprocessor=onnx_preprocessor,
)


jaqpot_model.convert_to_onnx()

# Upload to Jaqpot
jaqpot_model.deploy_on_jaqpot(
    jaqpot=jaqpot,
    name="Nanomaterial Classifier v8",
    description="Classifies nanomaterial types from TEM images.",
    visibility=ModelVisibility.PUBLIC,
)
