# coding: utf-8

"""
    Jaqpot API

    A modern RESTful API for model management and prediction services, built using Spring Boot and Kotlin. Supports seamless integration with machine learning workflows.

    The version of the OpenAPI document: 1.0.0
    Contact: upci.ntua@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jaqpotpy.api.openapi.models.model_task import ModelTask

class TestModelTask(unittest.TestCase):
    """ModelTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModelTask(self):
        """Test ModelTask"""
        # inst = ModelTask()

if __name__ == '__main__':
    unittest.main()
