# coding: utf-8

"""
    Jaqpot API

    A modern RESTful API for model management and prediction services, built using Spring Boot and Kotlin. Supports seamless integration with machine learning workflows.

    The version of the OpenAPI document: 1.0.0
    Contact: upci.ntua@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jaqpotpy.api.openapi.api.lead_api import LeadApi


class TestLeadApi(unittest.TestCase):
    """LeadApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LeadApi()

    def tearDown(self) -> None:
        pass

    def test_create_lead(self) -> None:
        """Test case for create_lead

        Create a Lead
        """
        pass

    def test_delete_lead_by_id(self) -> None:
        """Test case for delete_lead_by_id

        Delete a Lead by ID
        """
        pass

    def test_get_all_leads(self) -> None:
        """Test case for get_all_leads

        Get All Leads
        """
        pass

    def test_get_lead_by_id(self) -> None:
        """Test case for get_lead_by_id

        Get a Lead by ID
        """
        pass

    def test_update_lead_by_id(self) -> None:
        """Test case for update_lead_by_id

        Update a Lead by ID
        """
        pass


if __name__ == '__main__':
    unittest.main()
