# coding: utf-8

"""
    Jaqpot API

    A modern RESTful API for model management and prediction services, built using Spring Boot and Kotlin. Supports seamless integration with machine learning workflows.

    The version of the OpenAPI document: 1.0.0
    Contact: upci.ntua@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jaqpotpy.api.openapi.models.feature_type import FeatureType

class TestFeatureType(unittest.TestCase):
    """FeatureType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeatureType(self):
        """Test FeatureType"""
        # inst = FeatureType()

if __name__ == '__main__':
    unittest.main()
